# frozen_string_literal: true

require 'blacklight'

module Warclight
  class Engine < ::Rails::Engine
    Warclight::Engine.config.catalog_controller_field_accessors = %i[
			access_terms
			author
			category
			collection
			collection_name
			collection_number
			collections
			comments
			content
			content_encoding
			content_ffb
			content_first_bytes
			content_language
			content_length
			content_metadata
			content_metadata_ss
			content_text_length
			content_type
			content_type_droid
			content_type_ext
			content_type_full
			content_type_norm
			content_type_served
			content_type_tika
			content_type_version
			crawl_date
			crawl_dates
			crawl_year
			crawl_year_month
			crawl_year_month_day
			crawl_years
			description
			domain
			elements_used
			generator
			hash
			hashes
			host
			host_surt
			id_long
			image_colours
			image_dominant_colour
			image_faces
			image_faces_count
			image_height
			image_size
			image_width
			institution
			keywords
			last_modified
			last_modified_year
			license_url
			links
			links_domains
			links_hosts
			links_hosts_surts
			links_norm
			links_public_suffixes
			locations
			parse_error
			pdf_pdfa_errors
			pdf_pdfa_is_valid
			postcode
			postcode_district
			public_suffix
			publication_date
			publication_year
			record_type
			referrer_url
			resourcename
			sentiment
			sentiment_score
			server
			source_file
			source_file_offset
			status_code
			subject
			text
			title
			type
			url
			url_norm
			url_path
			url_type
			wayback_date
			wct_agency
			wct_collections
			wct_description
			wct_instance_id
			wct_subjects
			wct_target_id
			wct_title
			xml_root_ns
    ]
  end
end
