require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - '.internal_test_app/**/*'
    - '.internal_test_gem/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'lib/generators/warclight/templates/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.6
  DisplayCopNames: true

Rails:
  Enabled: true

Rails/OutputSafety:
  Exclude:
    - 'app/models/concerns/warclight/solr_document.rb'

Rails/RakeEnvironment:
  Exclude:
    - 'tasks/warclight.rake'

Layout/LineLength:
  Max: 120
  Exclude:
    - 'Gemfile'
    - 'spec/models/concerns/warclight/solr_document_spec.rb'

Metrics/ModuleLength:
  Max: 120

Metrics/ClassLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - !ruby/regexp /\.rake$/
    - 'warclight.gemspec'
    - 'spec/**/*'
    - 'lib/warclight/custom_document.rb'

Metrics/AbcSize:
  Exclude:
    - 'app/models/concerns/warclight/solr_document.rb' #Come back to this later

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/DescribeClass:
  Enabled: false

Style/DateTime:
  Exclude:
    - 'app/models/concerns/warclight/solr_document.rb' #Come back to this later

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'lib/warclight.rb'

Style/ExpandPathArguments:
  Exclude:
    - 'warclight.gemspec'
    - 'lib/generators/warclight/install_generator.rb'
    - 'lib/generators/warclight/update_generator.rb'

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/StringConcatenation:
  Exclude:
    - 'app/helpers/warclight_helper.rb'
    - 'app/models/concerns/warclight/solr_document.rb'

Bundler/DuplicatedGem:
  Enabled: false

Lint/UselessAssignment:
  Exclude:
    - 'app/models/concerns/warclight/solr_document.rb' #Come back to this later

Style/RescueStandardError:
  Exclude:
    - 'app/helpers/warclight_helper.rb'
