require: rubocop-rspec

AllCops:
  Exclude:
    - '.internal_test_app/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'lib/generators/warclight/templates/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.4
  DisplayCopNames: true

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'Gemfile'

Metrics/ModuleLength:
  Max: 120

Metrics/ClassLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - !ruby/regexp /\.rake$/
    - 'warclight.gemspec'
    - 'spec/**/*'
    - 'lib/warclight/custom_document.rb'

Performance/RegexpMatch:
  Enabled: false

Rails/OutputSafety:
  Exclude:
    - 'app/controllers/concerns/warclight/field_config_helpers.rb' # html_safe needs to be called to mimic BL JOIN behavior

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'lib/warclight.rb'

Bundler/DuplicatedGem:
  Enabled: false
