name: Warclight Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.7, 2.6, 2.5]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Setup Node
        run: npm install
      - name: Setup Warclight
        run: bundle install
      - name: Run tests
        run: bundle exec rake
      - name: Upload coverage report to Codecov
        run: bash <(curl -s https://codecov.io/bash)
