name: Warclight Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.6, 2.7, 3.0]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Setup Bundler (< 2.2)
        run: gem install bundler -v '< 2.2'
      - name: Setup Node
        run: npm install
      - name: Bundler version
        run: which bundle; bundle --version
      - name: Setup Warclight
        run: bundle install
      - name: Run tests
        run: bundle exec rake
      - name: Upload coverage report to Codecov
        run: bash <(curl -s https://codecov.io/bash)
