name: Warclight Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rails_version: [5.2.4.4, 6.0.3.4, 6.1.1]
        ruby: [2.6, 2.7]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Setup Bundler (< 2.2)
        run: gem uninstall bundler; gem install bundler -v '< 2.2'
      - name: Setup Node
        run: npm install
      - name: Bundler version
        run: which bundle; bundle --version
      - name: Setup Warclight with Rails ${{ matrix.rails_version }}
        run: bundle install
      - name: Run tests
        run: bundle exec rake
      - name: Upload coverage report to Codecov
        run: bash <(curl -s https://codecov.io/bash)
